#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6756003398                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : uk

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Highlight words, add notes and keep them visible on any webpage. iMeanIt is a Safari extension for storing vocabulary, tracking information and revisiting saved highlights. Notes persist across visits and can be exported as CSV for study use.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cenk Celik                                
your_link                                 : https://imeanitapp.github.io                     
your_city                                 : London                                
email_address                             : imeanitapp@proton.me
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : https://mastodon.social/@imeanitapp



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Highlight words. Forever.
    description                           : When you highlight a word, it remains highlighted across web.
    fontawesome_icon_name                 : highlighter
    
  - title                                 : Sticky notes.
    description                           : Add sticky notes to your highlights. Permanently.
    fontawesome_icon_name                 : note-sticky

  - title                                 : Export as CSV.
    description                           : Easily transfer your library into your favourite flashcard app.
    fontawesome_icon_name                 : file-export

  - title                                 : Learn natively.
    description                           : iMeanIt supports 27 languages. For now.
    fontawesome_icon_name                 : language
  
  - title                                 : Colourblind friendly.
    description                           : Our six-palette colour scheme accounts for everyone.
    fontawesome_icon_name                 : palette

  - title                                 : Available on your favourite device.
    description                           : iMeanIt is available on iOS/iPadOS/macOS with Liquid Glass design.
    fontawesome_icon_name                 : layer-group

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
